app_pages_list:
    pattern:  /{_application}/pages
    defaults: { _controller: AppBundle:Pages:list, _format: ~ }
    requirements:
        _method: GET
        _application: 'backend'
        
app_pages_get:
    pattern:  /{_application}/pages/{id}
    defaults: { _controller: AppBundle:Pages:get, _format: ~ }
    requirements:
        _method: GET
        id: '\w+'
        _application: 'backend'