# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #app.exception_controller:
    #    class: AppBundle\Controller\MainExceptionController
    #    arguments: ['@twig', '%kernel.debug%']
    mongo_doctrine_listener:
        class: AppBundle\Listener\MongoDoctrinePageListener
        tags: 
            -  { name: doctrine_mongodb.odm.event_listener, event: postLoad }
            -  { name: doctrine_mongodb.odm.event_listener, event: preLoad }
            
    # search engines        
    # like category and details
    app.category_search:
        class: AppBundle\Services\Search\CategorySearch
    
    # this is manager search service    
    app.search_manager:
        class: AppBundle\Services\Search\SearchManager
        arguments: ["@app.category_search", "@request_stack"]